licenses(["notice"]) 

filegroup(
  name = "license",
  srcs = ["LICENSE"],
)

java_import(
  name = "jsr305_annotations",
  visibility = ["//visibility:public"],    
  jars = [
    "jsr305-3.0.0.jar",
  ],
)