java_library(
  name = "acme",
  visibility = ["//visibility:public"],
  srcs = glob(["*.java"]),
  deps = [
    "@javax/servlet/javax/servlet-api//jar",
    "@org/eclipse/jetty/jetty-annotations//jar",
    "@org/eclipse/jetty/jetty-webapp//jar",
    "@org/mortbay/jasper/apache-jsp//jar",
    "@org/eclipse/jetty/apache-jstl//jar",
    "@org/eclipse/jetty/apache-jsp//jar",
  ],
)