# The following dependencies were calculated from:
# /Users/wangwei/Dev/git/great/lwms-web-basic/pom.xml

# com.googlecode.protobuf-java-format:protobuf-java-format:1.2
maven_jar(
	name="com/googlecode/protobuf-java-format/protobuf-java-format",
	artifact = "com.googlecode.protobuf-java-format:protobuf-java-format:1.2",
)
# org.springframework:spring-context:4.1.4.RELEASE
maven_jar(
	name="org/springframework/spring-context",
	artifact = "org.springframework:spring-context:4.1.4.RELEASE",
)
# org.springframework:spring-core:4.1.4.RELEASE
maven_jar(
	name="org/springframework/spring-core",
	artifact = "org.springframework:spring-core:4.1.4.RELEASE",
)
# org.slf4j:slf4j-api:1.7.10
maven_jar(
	name="org/slf4j/slf4j-api",
	artifact = "org.slf4j:slf4j-api:1.7.10",
)
# org.unbescape:unbescape:1.1.0.RELEASE
maven_jar(
	name="org/unbescape/unbescape",
	artifact = "org.unbescape:unbescape:1.1.0.RELEASE",
)
# org.eclipse.jetty:jetty-servlet:9.3.3.v20150827
maven_jar(
	name="org/eclipse/jetty/jetty-servlet",
	artifact = "org.eclipse.jetty:jetty-servlet:9.3.3.v20150827",
)
# org.slf4j:slf4j-log4j12:1.7.10
maven_jar(
	name="org/slf4j/slf4j-log4j12",
	artifact = "org.slf4j:slf4j-log4j12:1.7.10",
)
# log4j:log4j:1.2.17
maven_jar(
	name="log4j/log4j",
	artifact = "log4j:log4j:1.2.17",
)
# aopalliance:aopalliance:1.0
maven_jar(
	name="aopalliance/aopalliance",
	artifact = "aopalliance:aopalliance:1.0",
)
# org.eclipse.jetty:jetty-util:9.3.3.v20150827
maven_jar(
	name="org/eclipse/jetty/jetty-util",
	artifact = "org.eclipse.jetty:jetty-util:9.3.3.v20150827",
)
# com.google.protobuf:protobuf-java:3.0.0-beta-1
maven_jar(
	name="com/google/protobuf/protobuf-java",
	artifact = "com.google.protobuf:protobuf-java:3.0.0-beta-1",
)
# org.thymeleaf:thymeleaf-spring4:2.1.4.RELEASE
maven_jar(
	name="org/thymeleaf/thymeleaf-spring4",
	artifact = "org.thymeleaf:thymeleaf-spring4:2.1.4.RELEASE",
)
# com.beust:jcommander:1.48
maven_jar(
	name="com/beust/jcommander",
	artifact = "com.beust:jcommander:1.48",
)
# org.springframework:spring-web:4.1.4.RELEASE
maven_jar(
	name="org/springframework/spring-web",
	artifact = "org.springframework:spring-web:4.1.4.RELEASE",
)
# junit:junit:4.11
maven_jar(
	name="junit/junit",
	artifact = "junit:junit:4.11",
)
# org.eclipse.jetty:jetty-server:9.3.3.v20150827
maven_jar(
	name="org/eclipse/jetty/jetty-server",
	artifact = "org.eclipse.jetty:jetty-server:9.3.3.v20150827",
)
# org.springframework:spring-beans:4.1.4.RELEASE
maven_jar(
	name="org/springframework/spring-beans",
	artifact = "org.springframework:spring-beans:4.1.4.RELEASE",
)
# org.springframework:spring-expression:4.1.4.RELEASE
maven_jar(
	name="org/springframework/spring-expression",
	artifact = "org.springframework:spring-expression:4.1.4.RELEASE",
)
# javax.annotation:javax.annotation-api:1.2
maven_jar(
	name="javax/annotation/javax.annotation-api",
	artifact = "javax.annotation:javax.annotation-api:1.2",
)
# org.springframework:spring-aop:4.1.4.RELEASE
maven_jar(
	name="org/springframework/spring-aop",
	artifact = "org.springframework:spring-aop:4.1.4.RELEASE",
)
# org.javassist:javassist:3.16.1-GA
maven_jar(
	name="org/javassist/javassist",
	artifact = "org.javassist:javassist:3.16.1-GA",
)
# org.eclipse.jetty:jetty-http:9.3.3.v20150827
maven_jar(
	name="org/eclipse/jetty/jetty-http",
	artifact = "org.eclipse.jetty:jetty-http:9.3.3.v20150827",
)
# org.eclipse.jetty:jetty-security:9.3.3.v20150827
maven_jar(
	name="org/eclipse/jetty/jetty-security",
	artifact = "org.eclipse.jetty:jetty-security:9.3.3.v20150827",
)
# org.hamcrest:hamcrest-core:1.3
maven_jar(
	name="org/hamcrest/hamcrest-core",
	artifact = "org.hamcrest:hamcrest-core:1.3",
)
# org.thymeleaf:thymeleaf:2.1.4.RELEASE
maven_jar(
	name="org/thymeleaf/thymeleaf",
	artifact = "org.thymeleaf:thymeleaf:2.1.4.RELEASE",
)
# javax.servlet:javax.servlet-api:3.1.0
maven_jar(
	name="javax/servlet/javax.servlet-api",
	artifact = "javax.servlet:javax.servlet-api:3.1.0",
)
# ognl:ognl:3.0.8
maven_jar(
	name="ognl/ognl",
	artifact = "ognl:ognl:3.0.8",
)
# com.google.guava:guava:18.0
maven_jar(
	name="com/google/guava/guava",
	artifact = "com.google.guava:guava:18.0",
)
# commons-logging:commons-logging:1.2
maven_jar(
	name="commons-logging/commons-logging",
	artifact = "commons-logging:commons-logging:1.2",
)
# org.eclipse.jetty:jetty-xml:9.3.3.v20150827
maven_jar(
	name="org/eclipse/jetty/jetty-xml",
	artifact = "org.eclipse.jetty:jetty-xml:9.3.3.v20150827",
)
# org.eclipse.jetty:jetty-webapp:9.3.3.v20150827
maven_jar(
	name="org/eclipse/jetty/jetty-webapp",
	artifact = "org.eclipse.jetty:jetty-webapp:9.3.3.v20150827",
)
# org.eclipse.jetty:jetty-io:9.3.3.v20150827
maven_jar(
	name="org/eclipse/jetty/jetty-io",
	artifact = "org.eclipse.jetty:jetty-io:9.3.3.v20150827",
)
# org.springframework:spring-webmvc:4.1.4.RELEASE
maven_jar(
	name="org/springframework/spring-webmvc",
	artifact = "org.springframework:spring-webmvc:4.1.4.RELEASE",
)
#grpc_auth 
bind(
  name = "grpc_auth",
  actual = "//lib/grpc_auth:grpc_auth"
)
#grpc_core
bind(
  name = "grpc_core",
  actual = "//lib/grpc_core:grpc_core"
)
#grpc_netty
bind(
  name = "grpc_netty",
  actual = "//lib/grpc_netty:grpc_netty"
)
#grpc_okhttp
bind(
  name = "grpc_okhttp",
  actual = "//lib/grpc_okhttp:grpc_okhttp"
)
#grpc_protobuf
bind(
  name = "grpc_protobuf",
  actual = "//lib/grpc_protobuf:grpc_protobuf"
)
#grpc_stub
bind(
  name = "grpc_stub",
  actual = "//lib/grpc_stub:grpc_stub"
)
#jsr305
bind(
  name = "jsr305_annotations",
  actual = "//lib/jsr305_annotations:jsr305_annotations"
)
#ap def
bind(
  name = "ap_proto_java",
  actual = "//lib/proto_ap:ap_proto_java"
)
