# The following dependencies were calculated from:
# /Users/wangwei/Dev/git/jetty-springmvc-thymeleaf-template/pom.xml

# com.fasterxml.jackson.core:jackson-databind:2.4.2
maven_jar(
	name="com/fasterxml/jackson/core/jackson-databind",
	artifact = "com.fasterxml.jackson.core:jackson-databind:2.4.2",
)
# org.springframework:spring-context:4.1.4.RELEASE
maven_jar(
	name="org/springframework/spring-context",
	artifact = "org.springframework:spring-context:4.1.4.RELEASE",
)
# org.springframework:spring-core:4.1.4.RELEASE
maven_jar(
	name="org/springframework/spring-core",
	artifact = "org.springframework:spring-core:4.1.4.RELEASE",
)
# org.slf4j:slf4j-api:1.7.10
maven_jar(
	name="org/slf4j/slf4j-api",
	artifact = "org.slf4j:slf4j-api:1.7.10",
)
# io.dropwizard.metrics:metrics-healthchecks:3.1.0
maven_jar(
	name="io/dropwizard/metrics/metrics-healthchecks",
	artifact = "io.dropwizard.metrics:metrics-healthchecks:3.1.0",
)
# org.unbescape:unbescape:1.1.0.RELEASE
maven_jar(
	name="org/unbescape/unbescape",
	artifact = "org.unbescape:unbescape:1.1.0.RELEASE",
)
# aopalliance:aopalliance:1.0
maven_jar(
	name="aopalliance/aopalliance",
	artifact = "aopalliance:aopalliance:1.0",
)
# org.eclipse.jetty:jetty-util:9.2.6.v20141205
maven_jar(
	name="org/eclipse/jetty/jetty-util",
	artifact = "org.eclipse.jetty:jetty-util:9.2.6.v20141205",
)
# org.thymeleaf:thymeleaf-spring4:2.1.4.RELEASE
maven_jar(
	name="org/thymeleaf/thymeleaf-spring4",
	artifact = "org.thymeleaf:thymeleaf-spring4:2.1.4.RELEASE",
)
# org.ow2.asm:asm-tree:4.0
maven_jar(
	name="org/ow2/asm/asm-tree",
	artifact = "org.ow2.asm:asm-tree:4.0",
)
# org.springframework:spring-web:4.1.4.RELEASE
maven_jar(
	name="org/springframework/spring-web",
	artifact = "org.springframework:spring-web:4.1.4.RELEASE",
)
# junit:junit:4.11
maven_jar(
	name="junit/junit",
	artifact = "junit:junit:4.11",
)
# org.eclipse.jetty:jetty-server:9.2.6.v20141205
maven_jar(
	name="org/eclipse/jetty/jetty-server",
	artifact = "org.eclipse.jetty:jetty-server:9.2.6.v20141205",
)
# com.fasterxml.jackson.core:jackson-annotations:2.4.0
maven_jar(
	name="com/fasterxml/jackson/core/jackson-annotations",
	artifact = "com.fasterxml.jackson.core:jackson-annotations:2.4.0",
)
# io.dropwizard.metrics:metrics-json:3.1.0
maven_jar(
	name="io/dropwizard/metrics/metrics-json",
	artifact = "io.dropwizard.metrics:metrics-json:3.1.0",
)
# org.springframework:spring-beans:4.1.4.RELEASE
maven_jar(
	name="org/springframework/spring-beans",
	artifact = "org.springframework:spring-beans:4.1.4.RELEASE",
)
# antlr:antlr:2.7.7
maven_jar(
	name="antlr/antlr",
	artifact = "antlr:antlr:2.7.7",
)
# org.springframework:spring-expression:4.1.4.RELEASE
maven_jar(
	name="org/springframework/spring-expression",
	artifact = "org.springframework:spring-expression:4.1.4.RELEASE",
)
# io.dropwizard.metrics:metrics-servlets:3.1.0
maven_jar(
	name="io/dropwizard/metrics/metrics-servlets",
	artifact = "io.dropwizard.metrics:metrics-servlets:3.1.0",
)
# org.springframework.security:spring-security-config:3.2.5.RELEASE
maven_jar(
	name="org/springframework/security/spring-security-config",
	artifact = "org.springframework.security:spring-security-config:3.2.5.RELEASE",
)
# org.slf4j:jcl-over-slf4j:1.7.10
maven_jar(
	name="org/slf4j/jcl-over-slf4j",
	artifact = "org.slf4j:jcl-over-slf4j:1.7.10",
)
# io.dropwizard.metrics:metrics-core:3.1.0
maven_jar(
	name="io/dropwizard/metrics/metrics-core",
	artifact = "io.dropwizard.metrics:metrics-core:3.1.0",
)
# io.dropwizard.metrics:metrics-jvm:3.1.0
maven_jar(
	name="io/dropwizard/metrics/metrics-jvm",
	artifact = "io.dropwizard.metrics:metrics-jvm:3.1.0",
)
# org.springframework.security:spring-security-core:3.2.5.RELEASE
maven_jar(
	name="org/springframework/security/spring-security-core",
	artifact = "org.springframework.security:spring-security-core:3.2.5.RELEASE",
)
# org.ow2.asm:asm-analysis:4.0
maven_jar(
	name="org/ow2/asm/asm-analysis",
	artifact = "org.ow2.asm:asm-analysis:4.0",
)
# org.springframework:spring-aop:4.1.4.RELEASE
maven_jar(
	name="org/springframework/spring-aop",
	artifact = "org.springframework:spring-aop:4.1.4.RELEASE",
)
# ch.qos.logback:logback-core:1.1.2
maven_jar(
	name="ch/qos/logback/logback-core",
	artifact = "ch.qos.logback:logback-core:1.1.2",
)
# org.javassist:javassist:3.16.1-GA
maven_jar(
	name="org/javassist/javassist",
	artifact = "org.javassist:javassist:3.16.1-GA",
)
# org.ow2.asm:asm-util:4.0
maven_jar(
	name="org/ow2/asm/asm-util",
	artifact = "org.ow2.asm:asm-util:4.0",
)
# org.eclipse.jetty:jetty-http:9.2.6.v20141205
maven_jar(
	name="org/eclipse/jetty/jetty-http",
	artifact = "org.eclipse.jetty:jetty-http:9.2.6.v20141205",
)
# org.eclipse.jetty:jetty-security:9.2.6.v20141205
maven_jar(
	name="org/eclipse/jetty/jetty-security",
	artifact = "org.eclipse.jetty:jetty-security:9.2.6.v20141205",
)
# org.hamcrest:hamcrest-core:1.3
maven_jar(
	name="org/hamcrest/hamcrest-core",
	artifact = "org.hamcrest:hamcrest-core:1.3",
)
# org.thymeleaf:thymeleaf:2.1.4.RELEASE
maven_jar(
	name="org/thymeleaf/thymeleaf",
	artifact = "org.thymeleaf:thymeleaf:2.1.4.RELEASE",
)
# org.eclipse.jetty:jetty-xml:9.2.6.v20141205
maven_jar(
	name="org/eclipse/jetty/jetty-xml",
	artifact = "org.eclipse.jetty:jetty-xml:9.2.6.v20141205",
)
# javax.servlet:javax.servlet-api:3.1.0
maven_jar(
	name="javax/servlet/javax.servlet-api",
	artifact = "javax.servlet:javax.servlet-api:3.1.0",
)
# com.fasterxml.jackson.core:jackson-core:2.4.2
maven_jar(
	name="com/fasterxml/jackson/core/jackson-core",
	artifact = "com.fasterxml.jackson.core:jackson-core:2.4.2",
)
# org.springframework.security:spring-security-web:3.2.5.RELEASE
maven_jar(
	name="org/springframework/security/spring-security-web",
	artifact = "org.springframework.security:spring-security-web:3.2.5.RELEASE",
)
# ognl:ognl:3.0.8
maven_jar(
	name="ognl/ognl",
	artifact = "ognl:ognl:3.0.8",
)
# org.ow2.asm:asm-commons:4.0
maven_jar(
	name="org/ow2/asm/asm-commons",
	artifact = "org.ow2.asm:asm-commons:4.0",
)
# org.ow2.asm:asm:4.0
maven_jar(
	name="org/ow2/asm/asm",
	artifact = "org.ow2.asm:asm:4.0",
)
# org.eclipse.jetty:jetty-webapp:9.2.6.v20141205
maven_jar(
	name="org/eclipse/jetty/jetty-webapp",
	artifact = "org.eclipse.jetty:jetty-webapp:9.2.6.v20141205",
)
# ch.qos.logback:logback-classic:1.1.2
maven_jar(
	name="ch/qos/logback/logback-classic",
	artifact = "ch.qos.logback:logback-classic:1.1.2",
)
# org.eclipse.jetty:jetty-servlet:9.2.6.v20141205
maven_jar(
	name="org/eclipse/jetty/jetty-servlet",
	artifact = "org.eclipse.jetty:jetty-servlet:9.2.6.v20141205",
)
# org.eclipse.jetty:jetty-io:9.2.6.v20141205
maven_jar(
	name="org/eclipse/jetty/jetty-io",
	artifact = "org.eclipse.jetty:jetty-io:9.2.6.v20141205",
)
# org.codehaus.groovy:groovy:2.1.9
maven_jar(
	name="org/codehaus/groovy/groovy",
	artifact = "org.codehaus.groovy:groovy:2.1.9",
)
# org.springframework:spring-webmvc:4.1.4.RELEASE
maven_jar(
	name="org/springframework/spring-webmvc",
	artifact = "org.springframework:spring-webmvc:4.1.4.RELEASE",
)
