licenses(["notice"]) 

filegroup(
  name = "license",
  srcs = ["LICENSE"],
)

java_import(
  name = "ap_proto_java",
  visibility = ["//visibility:public"],    
  jars = [
    "libap_proto_java.jar",
  ],
)