java_library(
  name = "main",
  visibility = ["//visibility:public"],
  srcs = glob(["*.java"]),
  deps = [
  		"//src/main/java/com/luminate/wconsole/config:config",
        "@org/springframework/spring-context//jar",
        "@org/springframework/spring-web//jar",
        "@org/slf4j/slf4j-api//jar",
        "@org/thymeleaf/thymeleaf-spring4//jar",
        "@org/eclipse/jetty/jetty-webapp//jar",
        "@javax/servlet/javax.servlet-api//jar",
        "@org/springframework/spring-webmvc//jar",
        "@com/beust/jcommander//jar",
        "@com/google/guava/guava//jar",
  ],
)