licenses(["notice"]) 

filegroup(
  name = "license",
  srcs = ["LICENSE"],
)

java_import(
  name = "grpc_protobuf",
  visibility = ["//visibility:public"],    
  jars = [
    "libprotobuf.jar",
  ],
)