# The following dependencies were calculated from:
# /home/wangwei/Dev/git/great/jetty-springmvc-thymeleaf-template/pom.xml


# ca.unx:jetty-springmvc-thymeleaf-template:jar:0.0.1-SNAPSHOT
maven_jar(
    name = "org/codehaus/jackson/jackson-mapper-asl",
    artifact = "org.codehaus.jackson:jackson-mapper-asl:1.9.13",
)

# org.springframework:spring-context:jar:4.1.4.RELEASE
maven_jar(
    name = "org/aspectj/aspectjweaver",
    artifact = "org.aspectj:aspectjweaver:1.8.4",
)

# ca.unx:jetty-springmvc-thymeleaf-template:jar:0.0.1-SNAPSHOT
maven_jar(
    name = "org/springframework/security/spring-security-config",
    artifact = "org.springframework.security:spring-security-config:3.2.5.RELEASE",
)

# org.codehaus.groovy:groovy-all:jar:2.3.9
maven_jar(
    name = "com/beust/jcommander",
    artifact = "com.beust:jcommander:1.35",
)

# ca.unx:jetty-springmvc-thymeleaf-template:jar:0.0.1-SNAPSHOT
maven_jar(
    name = "org/codehaus/jackson/jackson-core-asl",
    artifact = "org.codehaus.jackson:jackson-core-asl:1.9.13",
)

maven_jar(
	   name = "org/thymeleaf/thymeleaf",
    artifact = "org.thymeleaf:thymeleaf:2.1.4.RELEASE",
)

# ca.unx:jetty-springmvc-thymeleaf-template:jar:0.0.1-SNAPSHOT
maven_jar(
    name = "io/dropwizard/metrics/metrics-servlets",
    artifact = "io.dropwizard.metrics:metrics-servlets:3.1.0",
)

# org.springframework:spring-context:jar:4.1.4.RELEASE
maven_jar(
    name = "joda-time/joda-time",
    artifact = "joda-time:joda-time:2.6",
)

# org.codehaus.groovy:groovy-all:jar:2.3.9 wanted version 4.11
# com.thoughtworks.qdox:qdox:jar:1.12.1
maven_jar(
    name = "junit/junit",
    artifact = "junit:junit:3.8.1",
)

# ca.unx:jetty-springmvc-thymeleaf-template:jar:0.0.1-SNAPSHOT
maven_jar(
    name = "org/slf4j/jcl-over-slf4j",
    artifact = "org.slf4j:jcl-over-slf4j:1.7.10",
)

# org.codehaus.groovy:groovy-all:jar:2.3.9
maven_jar(
    name = "org/apache/ant/ant",
    artifact = "org.apache.ant:ant:1.9.3",
)

# org.springframework:spring-context:jar:4.1.4.RELEASE
maven_jar(
    name = "org/springframework/spring-aop",
    artifact = "org.springframework:spring-aop:4.1.4.RELEASE",
)

# org.codehaus.groovy:groovy-all:jar:2.3.9
maven_jar(
    name = "org/apache/ivy/ivy",
    artifact = "org.apache.ivy:ivy:2.3.0",
)

# org.springframework:spring-context:jar:4.1.4.RELEASE
maven_jar(
    name = "org/springframework/spring-beans",
    artifact = "org.springframework:spring-beans:4.1.4.RELEASE",
)

# org.springframework:spring-context:jar:4.1.4.RELEASE
maven_jar(
    name = "org/jruby/jruby",
    artifact = "org.jruby:jruby:1.7.17",
)

# ca.unx:jetty-springmvc-thymeleaf-template:jar:0.0.1-SNAPSHOT
maven_jar(
    name = "org/springframework/spring-context",
    artifact = "org.springframework:spring-context:4.1.4.RELEASE",
)

# org.codehaus.groovy:groovy-all:jar:2.3.9
maven_jar(
    name = "com/thoughtworks/qdox/qdox",
    artifact = "com.thoughtworks.qdox:qdox:1.12.1",
)

# ca.unx:jetty-springmvc-thymeleaf-template:jar:0.0.1-SNAPSHOT
maven_jar(
    name = "org/thymeleaf/thymeleaf-spring4",
    artifact = "org.thymeleaf:thymeleaf-spring4:2.1.4.RELEASE",
)

# org.springframework:spring-context:jar:4.1.4.RELEASE
maven_jar(
    name = "org/codehaus/groovy/groovy-all",
    artifact = "org.codehaus.groovy:groovy-all:2.3.9",
)

# ca.unx:jetty-springmvc-thymeleaf-template:jar:0.0.1-SNAPSHOT
maven_jar(
    name = "org/springframework/spring-webmvc",
    artifact = "org.springframework:spring-webmvc:4.1.4.RELEASE",
)

# commons-logging:commons-logging:jar:1.1.1
maven_jar(
    name = "avalon-framework/avalon-framework",
    artifact = "avalon-framework:avalon-framework:4.1.3",
)

# ca.unx:jetty-springmvc-thymeleaf-template:jar:0.0.1-SNAPSHOT
maven_jar(
    name = "org/springframework/security/spring-security-web",
    artifact = "org.springframework.security:spring-security-web:3.2.5.RELEASE",
)

# org.codehaus.groovy:groovy-all:jar:2.3.9
maven_jar(
    name = "com/thoughtworks/xstream/xstream",
    artifact = "com.thoughtworks.xstream:xstream:1.4.7",
)

# org.springframework:spring-context:jar:4.1.4.RELEASE
maven_jar(
    name = "javax/validation/validation-api",
    artifact = "javax.validation:validation-api:1.0.0.GA",
)

# org.springframework:spring-context:jar:4.1.4.RELEASE
maven_jar(
    name = "org/springframework/spring-instrument",
    artifact = "org.springframework:spring-instrument:4.1.4.RELEASE",
)

# ca.unx:jetty-springmvc-thymeleaf-template:jar:0.0.1-SNAPSHOT
maven_jar(
    name = "ch/qos/logback/logback-classic",
    artifact = "ch.qos.logback:logback-classic:1.1.2",
)

# org.springframework:spring-context:jar:4.1.4.RELEASE
maven_jar(
    name = "org/springframework/spring-expression",
    artifact = "org.springframework:spring-expression:4.1.4.RELEASE",
)

# org.springframework:spring-context:jar:4.1.4.RELEASE
maven_jar(
    name = "org/springframework/spring-core",
    artifact = "org.springframework:spring-core:4.1.4.RELEASE",
)

# ca.unx:jetty-springmvc-thymeleaf-template:jar:0.0.1-SNAPSHOT
maven_jar(
    name = "org/springframework/spring-web",
    artifact = "org.springframework:spring-web:4.1.4.RELEASE",
)

# ca.unx:jetty-springmvc-thymeleaf-template:jar:0.0.1-SNAPSHOT
maven_jar(
    name = "org/eclipse/jetty/jetty-webapp",
    artifact = "org.eclipse.jetty:jetty-webapp:9.2.6.v20141205",
)

maven_jar(
    name = "org/eclipse/jetty/jetty-server",
    artifact = "org.eclipse.jetty:jetty-server:9.3.4.RC0",
)

# org.springframework:spring-context:jar:4.1.4.RELEASE
maven_jar(
    name = "javax/inject/javax/inject",
    artifact = "javax.inject:javax.inject:1",
)

# org.springframework:spring-context:jar:4.1.4.RELEASE
maven_jar(
    name = "org/beanshell/bsh",
    artifact = "org.beanshell:bsh:2.0b4",
)

# org.codehaus.groovy:groovy-all:jar:2.3.9
maven_jar(
    name = "bsf/bsf",
    artifact = "bsf:bsf:2.4.0",
)

# org.springframework:spring-context:jar:4.1.4.RELEASE
maven_jar(
    name = "org/hibernate/hibernate-validator",
    artifact = "org.hibernate:hibernate-validator:4.3.2.Final",
)

# org.springframework:spring-context:jar:4.1.4.RELEASE
maven_jar(
    name = "javax/ejb/ejb-api",
    artifact = "javax.ejb:ejb-api:3.0",
)

# com.thoughtworks.qdox:qdox:jar:1.12.1
maven_jar(
    name = "ant/ant",
    artifact = "ant:ant:1.5.1",
)

# joda-time:joda-time:jar:2.6
maven_jar(
    name = "org/joda/joda-convert",
    artifact = "org.joda:joda-convert:1.2",
)

# commons-logging:commons-logging:jar:1.1.1
maven_jar(
    name = "logkit/logkit",
    artifact = "logkit:logkit:1.0.1",
)

# org.springframework:spring-context:jar:4.1.4.RELEASE
maven_jar(
    name = "javax/enterprise/concurrent/javax/enterprise/concurrent-api",
    artifact = "javax.enterprise.concurrent:javax.enterprise.concurrent-api:1.0",
)

# commons-logging:commons-logging:jar:1.1.1
maven_jar(
    name = "log4j/log4j",
    artifact = "log4j:log4j:1.2.12",
)

# ca.unx:jetty-springmvc-thymeleaf-template:jar:0.0.1-SNAPSHOT
maven_jar(
    name = "org/slf4j/slf4j-api",
    artifact = "org.slf4j:slf4j-api:1.7.10",
)

# org.apache.ant:ant:jar:1.9.3
maven_jar(
    name = "org/apache/ant/ant-launcher",
    artifact = "org.apache.ant:ant-launcher:1.9.3",
)

# bsf:bsf:jar:2.4.0 wanted version 1.0.4
# org.codehaus.groovy:groovy-all:jar:2.3.9
maven_jar(
    name = "commons-logging/commons-logging",
    artifact = "commons-logging:commons-logging:1.1.1",
)

# org.codehaus.groovy:groovy-all:jar:2.3.9
maven_jar(
    name = "org/fusesource/jansi/jansi",
    artifact = "org.fusesource.jansi:jansi:1.11",
)

# ca.unx:jetty-springmvc-thymeleaf-template:jar:0.0.1-SNAPSHOT
maven_jar(
    name = "javax/servlet/javax/servlet-api",
    artifact = "javax.servlet:javax.servlet-api:3.1.0",
)

# ca.unx:jetty-springmvc-thymeleaf-template:jar:0.0.1-SNAPSHOT
maven_jar(
    name = "org/springframework/security/spring-security-core",
    artifact = "org.springframework.security:spring-security-core:3.2.5.RELEASE",
)

# ca.unx:jetty-springmvc-thymeleaf-template:jar:0.0.1-SNAPSHOT
maven_jar(
    name = "io/dropwizard/metrics/metrics-core",
    artifact = "io.dropwizard.metrics:metrics-core:3.1.0",
)

# ca.unx:jetty-springmvc-thymeleaf-template:jar:0.0.1-SNAPSHOT
maven_jar(
    name = "org/codehaus/groovy/groovy",
    artifact = "org.codehaus.groovy:groovy:2.1.9",
)

# org.codehaus.groovy:groovy-all:jar:2.3.9
maven_jar(
    name = "jline/jline",
    artifact = "jline:jline:2.11",
)

# org.springframework:spring-context:jar:4.1.4.RELEASE
maven_jar(
    name = "org/eclipse/persistence/javax/persistence",
    artifact = "org.eclipse.persistence:javax.persistence:2.0.0",
)

